config/routes.rb
CarPooling::Application.routes.draw do
  resources :cerpoolingrequests

  resources :travels

  resources :cities

  resources :users

  resources :notifications

end

app/models/cerpoolingrequest.rb
class Cerpoolingrequest < ActiveRecord::Base 
	belongs_to :user
	belongs_to :travel


	validates :email, format: {with: /\w+@\w+\.com/}
	validates :password, presence: true
	
  attr_accessible :email, :password, :prefer_from, :prefer_to, :travel_id, :user_id
end

app/controllers/cerpoolingrequests_controller.rb
class CerpoolingrequestsController < ApplicationController
  # GET /cerpoolingrequests
  # GET /cerpoolingrequests.json
  def index
    @cerpoolingrequests = Cerpoolingrequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cerpoolingrequests }
    end
  end

  # GET /cerpoolingrequests/1
  # GET /cerpoolingrequests/1.json
  def show
    @cerpoolingrequest = Cerpoolingrequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cerpoolingrequest }
    end
  end

  # GET /cerpoolingrequests/new
  # GET /cerpoolingrequests/new.json
  def new
    @cerpoolingrequest = Cerpoolingrequest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cerpoolingrequest }
    end
  end

  # GET /cerpoolingrequests/1/edit
  def edit
    @cerpoolingrequest = Cerpoolingrequest.find(params[:id])
  end

  # POST /cerpoolingrequests
  # POST /cerpoolingrequests.json
  def create
    @cerpoolingrequest = Cerpoolingrequest.new(params[:cerpoolingrequest])

    respond_to do |format|
      if @cerpoolingrequest.save
        format.html { redirect_to @cerpoolingrequest, notice: 'Cerpoolingrequest was successfully created.' }
        format.json { render json: @cerpoolingrequest, status: :created, location: @cerpoolingrequest }
      else
        format.html { render action: "new" }
        format.json { render json: @cerpoolingrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cerpoolingrequests/1
  # PUT /cerpoolingrequests/1.json
  def update
    @cerpoolingrequest = Cerpoolingrequest.find(params[:id])

    respond_to do |format|
      if @cerpoolingrequest.update_attributes(params[:cerpoolingrequest])
        format.html { redirect_to @cerpoolingrequest, notice: 'Cerpoolingrequest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cerpoolingrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cerpoolingrequests/1
  # DELETE /cerpoolingrequests/1.json
  def destroy
    @cerpoolingrequest = Cerpoolingrequest.find(params[:id])
    @cerpoolingrequest.destroy

    respond_to do |format|
      format.html { redirect_to cerpoolingrequests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cerpoolingrequests_helper.rb
module CerpoolingrequestsHelper
end

app/views/cerpoolingrequests/_form.html.erb
<%= form_for(@cerpoolingrequest) do |f| %>
  <% if @cerpoolingrequest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cerpoolingrequest.errors.count, "error") %> prohibited this cerpoolingrequest from being saved:</h2>

      <ul>
      <% @cerpoolingrequest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :travel_id %><br />
    <%= f.number_field :travel_id %>
  </div>
  <div class="field">
    <%= f.label :prefer_from %><br />
    <%= f.text_field :prefer_from %>
  </div>
  <div class="field">
    <%= f.label :prefer_to %><br />
    <%= f.text_field :prefer_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cerpoolingrequests/edit.html.erb
<h1>Editing cerpoolingrequest</h1>

<%= render 'form' %>

<%= link_to 'Show', @cerpoolingrequest %> |
<%= link_to 'Back', cerpoolingrequests_path %>

app/views/cerpoolingrequests/index.html.erb
<h1>Listing cerpoolingrequests</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th>User</th>
    <th>Travel</th>
    <th>Prefer from</th>
    <th>Prefer to</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cerpoolingrequests.each do |cerpoolingrequest| %>
  <tr>
    <td><%= cerpoolingrequest.email %></td>
    <td><%= cerpoolingrequest.password %></td>
    <td><%= cerpoolingrequest.user_id %></td>
    <td><%= cerpoolingrequest.travel_id %></td>
    <td><%= cerpoolingrequest.prefer_from %></td>
    <td><%= cerpoolingrequest.prefer_to %></td>
    <td><%= link_to 'Show', cerpoolingrequest %></td>
    <td><%= link_to 'Edit', edit_cerpoolingrequest_path(cerpoolingrequest) %></td>
    <td><%= link_to 'Destroy', cerpoolingrequest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cerpoolingrequest', new_cerpoolingrequest_path %>

app/views/cerpoolingrequests/new.html.erb
<h1>New cerpoolingrequest</h1>

<%= render 'form' %>

<%= link_to 'Back', cerpoolingrequests_path %>

app/views/cerpoolingrequests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @cerpoolingrequest.email %>
</p>

<p>
  <b>Password:</b>
  <%= @cerpoolingrequest.password %>
</p>

<p>
  <b>User:</b>
  <%= @cerpoolingrequest.user_id %>
</p>

<p>
  <b>Travel:</b>
  <%= @cerpoolingrequest.travel_id %>
</p>

<p>
  <b>Prefer from:</b>
  <%= @cerpoolingrequest.prefer_from %>
</p>

<p>
  <b>Prefer to:</b>
  <%= @cerpoolingrequest.prefer_to %>
</p>


<%= link_to 'Edit', edit_cerpoolingrequest_path(@cerpoolingrequest) %> |
<%= link_to 'Back', cerpoolingrequests_path %>